export const indexHTML = '<!DOCTYPE html>'
    + '<html>'
    + '<head>'
    + '<title>Rummikub</title>'
    + '<meta charset="utf-8">'
    + '</head>'
    + '<body>'
    + '<div id="rummikub-game"></div>'
    + '<script src="app.js"></script>'
    + '</body>'
    + '</html>';
